### ISSUE TITLE
[오류] zipfile.BadZipFile: File is not a zip file 에러

### ISSUE THREAD

**Issue by ffalswo2** [jmjeon94/N2T#20]
```
/Users/minjae/.n2t/Export-704fbe83-9204-45ea-b56c-65924ef18565.zip
Traceback (most recent call last):
  File "/Users/minjae/Documents/N2T/main.py", line 171, in <module>
    client.posts()
  File "/Users/minjae/Documents/N2T/main.py", line 76, in posts
    page_path = get_html_path(download_dir)
  File "/Users/minjae/Documents/N2T/utils/utils.py", line 114, in get_html_path
    zip = zipfile.ZipFile(zip_fp)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
계속 잘쓰다가 해당 에러에서 해결을 못하고 있습니다.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/60292150/227783658-39e563a3-ac72-4f8f-b015-4b42421671e3.png">
path값도 일치하게 잘 보내지고 있는 것 같은데 확인해보니 zip파일이 아니라서 안되는 것 같습니다. 혹시 이유로 추측가시는게 있을까요?

**Comment by aaajeong** [comment]
저도 동일한 에러 해결하고 있습니다. 🥹
맥북이라 zip 파일 압축하는데 오류가 있는 것 같아서 파일 압축 후 폴더에서 따로 확인해봤는데요,
`# self.download_file(export_link, self.download_path.expanduser() / f'Export-{page_id}.zip')`
여기서 생성된 파일 압축해제가 아예 안되고 있고, keka 라는 압축해제 프로그램을 사용해도 오류는 해결되지 않고 있습니다.
@ffalswo2 님은 윈도우 환경이신가요? 그런데도 발생하신거면,,,제 맥북 압축 프로그램의 문제는 아닌가보네요...!

아마 zipfile 라이브러리에서 발생하는 오류가 아닐까 생각해봅니다...

저는 python 3.7 사용하고 있어서 3.9로 업데이트 후 재시도 해도 동일한 문제가 발생하고있고, zip 대신 tar나 tar.gz로 압축해제 시도해보고 있습니다.
혹시 비슷한 문제 해결하신 분 있으면 댓글 부탁드립니다.

**Comment by aaajeong** [comment]
앗, 다시보니 맥북을 사용하고 계시네요...! 
맥북 기본 압축프로그램에서 문제가 있는 게 맞나보군요...!

**Comment by jmjeon94** [comment]
안녕하세요 zip 파일의 압축 문제가 아니라,
notion의 api 방식 변경으로 인해 정상적으로 페이지가 내보내기 되지 않아서 그렇습니다.
해당 이슈를 수정하였으니 코드를 다시 받아서 사용해보세요!

https://github.com/jmjeon94/N2T/commit/73f1a4c40f4bd83ab8d69410ddeb01b8e8de82d8

**Comment by PyoSH** [comment]
![Screenshot from 2023-03-28 20-28-47](https://user-images.githubusercontent.com/42665051/228222242-191cac2b-3c15-4170-a26c-5f08d2c8a5e4.png)
안녕하세요! 만들어주신 코드 덕분에 블로그 작성을 쉽게 하고 있습니다 :) 감사합니다! 
저도 동일한 이슈가 생겨서 새로 코드를 받아 작동했는데, 해결되지 않았습니다 :( 
다른 분들은 해결이 되셨나요?

**Comment by aaajeong** [comment]
저는 잘 작동되는 것을 확인했습니다🙌👍
