### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' 에러 도와주세요ㅠ

### ISSUE THREAD

**Issue by Soyunnlee** [jmjeon94/N2T#34]
N2T 이용하면서 문제없지 잘 작동 되었었는데, 그러던중

`[진행중] Tistory Authorize code, Access Token 발급 완료!
100%|█████████████████████████████████████████████████████████| 6.00k/6.00k [00:00<00:00, 1.80MiB/s]
[진행중] Notion Page Export Complete in /Users/isoyun/.n2t/Export-e35b2882-f9fb-4b40-8021-b353e7fc2bd3.zip
[진행중] 1번째 페이지 다운로드 완료...
        [진행중] parsing 완료... posting 완료... [[React] Prettier 설정 e35b2882f9fb4b408021b353e7fc2bd3.html]
Traceback (most recent call last):
  File "main.py", line 184, in <module>
    client.posts()
  File "main.py", line 79, in posts
    self.parse_and_post(page, page_path)
  File "main.py", line 162, in parse_and_post
    page[0].set_property(cfg.NOTION.COLUMN.URL, BeautifulSoup(resp_post.text, 'lxml').find('url').text)
AttributeError: 'NoneType' object has no attribute 'text'
`

이런 에러가 떠서 문의 드립니다ㅠ 도움을 얻을 수 있을까요

**Comment by HY-PARK** [comment]
@Soyunnlee 
TistoryClient.py를 다음과 같이 수정하니, 잘되네요
<img width="1826" alt="image" src="https://github.com/jmjeon94/N2T/assets/54871310/d326f8c5-e4a5-4093-9b69-9206e8ed5b48">
