### ISSUE TITLE
[Beautiful Soup 읽기 오류]

### ISSUE THREAD

**Issue by kdh4672** [jmjeon94/N2T#9]
SelenumClient.py의
(line 73~76)
```
resp = self.driver.get(authorize_url)
soup = BeautifulSoup(resp, 'html.parser')

code = soup.script.text.split('code=')[1].split('&state')[0]
```
에서 resp를 불러올 때 제대로 안불러져서 이런 오류가 나는 것 같습니다.
(원래 잘 되던것이 이런 오류가 발생하네요 ㅠ)

- 오류 메시지

```
Traceback (most recent call last):
  File "/Users/daehyeon/Codes/N2T/main.py", line 163, in <module>
    client = Notion2Tistory(cfg, sleep_time=5, selenium_debug=False)
  File "/Users/daehyeon/Codes/N2T/main.py", line 56, in __init__
    authorize_code = self.s_client.get_tistory_authorize_code(cfg.TISTORY.CLIENT_ID, cfg.TISTORY.REDIRECT_URI)
  File "/Users/daehyeon/Codes/N2T/clients/SeleniumClient.py", line 76, in get_tistory_authorize_code
    code = soup.script.text.split('code=')[1].split('&state')[0]
IndexError: list index out of range

[완료] 프로그램 종료.
```

### 질문

혹시 카카오 데이터 센터 화재로 스킨이 아직 복구 안 된것과 관련있는 오류인가요?

### 늘 잘 사용하고 있습니다. 감사합니다.

**Comment by jmjeon94** [comment]
안녕하세요. 답변이 많이 늦었네요. 
티스토리의 카카오 로그인 페이지 URL이 수정되면서 발생하는 오류인 것 같습니다.
수정된 URL로 코드도 수정하였으니 새롭게 받아서 사용하시면 될 것 같습니다.

#10 

감사합니다!
